	set_property PACKAGE_PIN W5 [get_ports clk]
	set_property IOSTANDARD LVCMOS33 [get_ports clk]

	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

	set_property PACKAGE_PIN A14 [get_ports {rowsOut[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {rowsOut[0]}] 
	set_property PACKAGE_PIN A16 [get_ports {rowsOut[1]}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {rowsOut[1]}] 
  	set_property PACKAGE_PIN B15 [get_ports {rowsOut[2]}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {rowsOut[2]}] 
  	set_property PACKAGE_PIN B16 [get_ports {rowsOut[3]}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {rowsOut[3]}] 
  	set_property PACKAGE_PIN A15 [get_ports {rowsOut[4]}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {rowsOut[4]}] 
  	set_property PACKAGE_PIN A17 [get_ports {rowsOut[5]}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {rowsOut[5]}] 
  	set_property PACKAGE_PIN C15 [get_ports {rowsOut[6]}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {rowsOut[6]}]  
  	set_property PACKAGE_PIN C16 [get_ports {rowsOut[7]}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {rowsOut[7]}]
	set_property PACKAGE_PIN K17 [get_ports {ds}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {ds}]
  	set_property PACKAGE_PIN M18 [get_ports {oe}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {oe}] 
  	set_property PACKAGE_PIN N17 [get_ports {stcp}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {stcp}]  
  	set_property PACKAGE_PIN P18 [get_ports {shcp}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {shcp}] 
  	set_property PACKAGE_PIN L17 [get_ports {mr}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {mr}] 