# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param synth.incrementalSynthesisCache C:/Users/umityigitbsrn/Desktop/cs223Project/.Xil/Vivado-5160-DESKTOP-C4M6KNV/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.cache/wt [current_project]
set_property parent.project_path C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/FourRegister.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/SevSeg_4Digit.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/buttonDebouncerMain.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/clockDivider.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/converter.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/decoder2x4.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/doubleArrayConverter.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/fourMode.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/gameController.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/gameData.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/mux1x2.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/mux2x115.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/mux4x2.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/mux4x264.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/oneMode.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/partAController.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/partADatapath.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/partAMain.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/partBController.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/partBDatapath.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/partBMain.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/partCController.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/partCDatapath.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/partCDatapath2.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/partCMain.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/sixtyFourRegister.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/sixtyFourRegister2.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/threeMode.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/twoMode.sv
  C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/sources_1/new/gameMain.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/constrs_1/new/contraint.xdc
set_property used_in_implementation false [get_files C:/Users/umityigitbsrn/Desktop/cs223Project/cs223Project.srcs/constrs_1/new/contraint.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top gameMain -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef gameMain.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file gameMain_utilization_synth.rpt -pb gameMain_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
